# Generated by Django 4.2 on 2025-09-09 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('source', models.CharField(default='site_web', max_length=100)),
            ],
            options={
                'verbose_name': 'Inscription newsletter',
                'verbose_name_plural': 'Inscriptions newsletter',
                'db_table': 'newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('fonction', models.CharField(max_length=100)),
                ('etablissement', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'db_table': 'temoignages',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('nom_etablissement', models.CharField(max_length=200)),
                ('type_etablissement', models.CharField(choices=[('ecole_primaire', 'École primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université'), ('centre_formation', 'Centre de formation'), ('autre', 'Autre')], max_length=50)),
                ('nombre_enseignants', models.PositiveIntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('contacte', 'Contacté'), ('demo_planifiee', 'Démo planifiée'), ('convertis', 'Converti'), ('abandonne', 'Abandonné')], default='en_attente', max_length=20)),
                ('notes_commerciales', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_contact', models.DateTimeField(blank=True, null=True)),
                ('date_demo', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='site_web', max_length=100)),
                ('commercial_assigné', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de démonstration',
                'verbose_name_plural': 'Demandes de démonstration',
                'db_table': 'demandes_demo',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('type_message', models.CharField(choices=[('question_generale', 'Question générale'), ('support_technique', 'Support technique'), ('demande_commerciale', 'Demande commerciale'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], default='question_generale', max_length=50)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('ferme', 'Fermé')], default='nouveau', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('reponse', models.TextField(blank=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'db_table': 'messages_contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('resume', models.TextField(max_length=500)),
                ('contenu', models.TextField()),
                ('categorie', models.CharField(choices=[('actualites', 'Actualités'), ('tutoriels', 'Tutoriels'), ('cas_usage', "Cas d'usage"), ('technique', 'Technique'), ('partenaires', 'Partenaires')], max_length=50)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('mots_cles', models.CharField(blank=True, max_length=200)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'db_table': 'articles_blog',
                'ordering': ['-date_publication'],
            },
        ),
    ]
